import { Box, Button, Input, Text } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import React from "react";

const Home: NextPage = () => {
  const [value, setValue] = React.useState("");

  const handleChange = (event: {
    target: { value: React.SetStateAction<string> };
  }) => setValue(event.target.value);

  const handleClick = async () => {
    return await fetch(`/api/feed`, {
      method: "post",
      headers: {
        Accept: "application/json",
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        url: value,
      }),
    }).then((res) => res.json());
  };

  return (
    <div>
      <Head>
        <title>RSS feed reader</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box p={4}>
        <Text>RSS feed reader</Text>
        <Text mb="8px">Value: {value}</Text>
        <Input
          value={value}
          onChange={handleChange}
          placeholder="Here is a sample placeholder"
          size="sm"
        />
        <Button onClick={handleClick}> Show Feed Results </Button>
      </Box>
    </div>
  );
};

export default Home;
