import { Box, Button, Input, Text } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import React from "react";
import Parser from "rss-parser";

const Home: NextPage = () => {
  const [value, setValue] = React.useState("");
  const handleChange = (event: {
    target: { value: React.SetStateAction<string> };
  }) => setValue(event.target.value);

  const handleClick = async () => {
    const url = value;
    const CORS_PROXY =
      process.env.NEXT_PUBLIC_ENV === "development"
        ? `https://cors-anywhere.herokuapp.com/`
        : "";
    const parser = new Parser();
    return await parser.parseURL(`${CORS_PROXY}${url}`);
  };

  return (
    <div>
      <Head>
        <title>RSS feed reader</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box p={4}>
        <Text>RSS feed reader</Text>
        <Text mb="8px">Value: {value}</Text>
        <Input
          value={value}
          onChange={handleChange}
          placeholder="Here is a sample placeholder"
          size="sm"
        />
        <Button onClick={handleClick}> Show Feed Results </Button>
      </Box>
    </div>
  );
};

export default Home;
